### Set the base image to the one built before
FROM eap6.4-appd

### File Author / Maintainer
MAINTAINER "Robert Greathouse" "cyotee@gmail.com"

### Add application to JBoss EAP
COPY app/ticket-monster.war $JBOSS_HOME/standalone/deployments/
